export const servicesData = {
  fr: {
    implants: {
      slug: 'implants-dentaires',
      title: 'Implants dentaires',
      metaTitle: 'Implants dentaires Montréal | Dr Serge Chaussé',
      metaDescription: 'Expert en implants dentaires à Montréal depuis 40 ans. Dr Serge Chaussé offre des solutions permanentes pour remplacer vos dents manquantes. Consultation gratuite.',
      hero: {
        tagline: 'La solution permanente',
        title: 'Implants dentaires',
        subtitle: "Retrouvez un sourire naturel et une fonction masticatoire complète grâce aux implants dentaires de titane posés par un expert de 40 ans d'expérience.",
      },
      intro: "L'implant dentaire est aujourd'hui la solution la plus avancée pour remplacer une ou plusieurs dents manquantes. Contrairement aux prothèses amovibles ou aux bridges, l'implant s'intègre directement dans l'os de la mâchoire, offrant une stabilité et une apparence identiques à une dent naturelle.",
      benefits: [
        { icon: '🦷', title: 'Résultat permanent', desc: 'Un implant bien posé dure toute une vie avec un entretien minimal.' },
        { icon: '💪', title: 'Solidité maximale', desc: 'Mangez, parlez et souriez sans restriction ni inconfort.' },
        { icon: '🎨', title: 'Esthétique naturelle', desc: "La couronne est taillée sur mesure pour s'intégrer parfaitement." },
        { icon: '🦴', title: 'Préservation osseuse', desc: "L'implant stimule l'os et prévient la résorption osseuse." },
      ],
      process: [
        { step: '01', title: 'Consultation et examen', desc: 'Radiographies 3D, bilan de santé, plan de traitement personnalisé.' },
        { step: '02', title: "Pose de l'implant", desc: "Insertion chirurgicale de la vis de titane dans l'os sous anesthésie locale." },
        { step: '03', title: 'Ostéointégration', desc: "Période de guérison de 3 à 6 mois où l'os fusionne avec l'implant." },
        { step: '04', title: 'Couronne définitive', desc: 'Pose de la couronne sur mesure. Résultat final naturel et durable.' },
      ],
      faq: [
        { q: 'Est-ce douloureux?', a: "La pose se fait sous anesthésie locale. La plupart des patients comparent l'expérience à une extraction dentaire. Des analgésiques suffisent après l'intervention." },
        { q: 'Combien de temps dure un implant?', a: 'Un implant bien intégré peut durer toute une vie. Les études à long terme montrent des taux de succès supérieurs à 95% après 20 ans.' },
        { q: 'Suis-je un bon candidat?', a: 'La plupart des adultes en bonne santé sont éligibles. Un examen osseux et un bilan de santé permettront de confirmer votre candidature.' },
        { q: 'Quel est le coût?', a: "Le coût varie selon le nombre d'implants et les traitements préalables. Une consultation permettra d'établir un devis précis. Certains régimes d'assurance couvrent une partie des frais." },
        { q: 'Combien de temps pour le traitement complet?', a: 'De 4 à 9 mois selon votre situation, incluant la période de guérison osseuse. Des implants provisoires peuvent être posés pour cette période.' },
      ],
      videoId: 'k649xMCcHLo',
      videoTitle: 'Dr Chaussé explique les implants dentaires',
    },
    allon4: {
      slug: 'all-on-4',
      title: 'All-on-4',
      metaTitle: 'All-on-4 Montréal | Prothèse complète sur implants | Dr Chaussé',
      metaDescription: 'Technique All-on-4 à Montréal : retrouvez toutes vos dents en une seule journée. Dr Serge Chaussé, expert certifié Trinon depuis 2007.',
      hero: {
        tagline: 'Toutes vos dents en une journée',
        title: 'All-on-4',
        subtitle: "La révolution en réhabilitation dentaire complète. Quatre implants suffisent pour supporter une arcade entière de dents fixes et permanentes.",
      },
      intro: "Le All-on-4 est une technique chirurgicale révolutionnaire qui permet de remplacer toutes les dents d'une arcade (supérieure ou inférieure) avec seulement quatre implants stratégiquement placés. Le Dr Chaussé, formateur international certifié, maîtrise cette technique depuis plus de 15 ans.",
      benefits: [
        { icon: '⚡', title: 'Résultat immédiat', desc: "Des dents provisoires fixes sont posées le jour même de l'opération." },
        { icon: '🦴', title: "Moins d'implants", desc: 'Seulement 4 implants pour une arcade complète, évitant souvent les greffes.' },
        { icon: '💰', title: 'Solution économique', desc: "Plus abordable qu'un implant par dent pour une arcade complète." },
        { icon: '🌟', title: 'Qualité de vie', desc: 'Mangez ce que vous voulez dès les premières semaines.' },
      ],
      process: [
        { step: '01', title: 'Bilan complet', desc: 'Scanner 3D, planification chirurgicale virtuelle, choix du sourire.' },
        { step: '02', title: 'Chirurgie', desc: 'Pose des 4 implants et extraction des dents restantes si nécessaire.' },
        { step: '03', title: 'Prothèse provisoire', desc: 'Pose d\'une prothèse fixe temporaire le jour même.' },
        { step: '04', title: 'Prothèse définitive', desc: 'Après 4-6 mois, pose de la prothèse définitive en zircone.' },
      ],
      faq: [
        { q: 'Suis-je candidat au All-on-4?', a: "Toute personne ayant perdu la majorité de ses dents ou souffrant de problèmes dentaires sévères peut être candidate. Une évaluation complète est nécessaire." },
        { q: 'Faut-il une greffe osseuse?', a: "L'un des avantages majeurs du All-on-4 est que les implants inclinés permettent souvent d'éviter les greffes osseuses, même en cas de résorption avancée." },
        { q: 'Les dents provisoires sont-elles fonctionnelles?', a: 'Oui, vous pouvez manger dès le lendemain, mais une diète molle est recommandée pendant les premiers mois.' },
        { q: 'Quelle est la durée de vie de la prothèse?', a: 'Les implants durent toute une vie. La prothèse en zircone peut durer 15-20 ans avant d\'être remplacée.' },
      ],
      videoId: 'XCnOcDKxFGE',
      videoTitle: 'Dr Chaussé présente le All-on-4',
    },
    'chirurgie-dents-de-sagesse': {
      slug: 'chirurgie-dents-de-sagesse',
      title: 'Chirurgie des dents de sagesse',
      metaTitle: 'Chirurgie dents de sagesse Montréal | Dr Serge Chaussé',
      metaDescription: "Extraction de dents de sagesse à Montréal. Dr Serge Chaussé, 40 ans d'expérience en chirurgie buccale.",
      hero: {
        tagline: 'Extraction sécuritaire et sans douleur',
        title: 'Chirurgie des dents de sagesse',
        subtitle: "Le Dr Chaussé réalise l'extraction des dents de sagesse avec précision et confort, en clinique, sous anesthésie locale ou sédation.",
      },
      intro: "L'extraction des dents de sagesse est l'une des chirurgies buccales les plus courantes. Qu'elles soient incluses, semi-incluses ou en éruption difficile, le Dr Chaussé les traite directement en clinique, sans hospitalisation.",
      benefits: [
        { icon: '🏥', title: 'En clinique', desc: "Pas besoin d'hôpital — l'extraction se fait directement à la clinique." },
        { icon: '💉', title: 'Anesthésie locale', desc: 'Procédure confortable sous anesthésie locale ou sédation consciente.' },
        { icon: '📋', title: 'Suivi post-opératoire', desc: 'Instructions claires et suivi rigoureux pour une guérison optimale.' },
        { icon: '🦷', title: 'Expérience chirurgicale', desc: "40 ans d'expérience en chirurgie buccale et implantologie." },
      ],
      process: [
        { step: '01', title: 'Évaluation radiologique', desc: "Radiographie panoramique pour planifier l'extraction selon la position des dents." },
        { step: '02', title: 'Anesthésie', desc: "Administration de l'anesthésie locale pour un confort maximal." },
        { step: '03', title: 'Extraction', desc: 'Retrait précis de la dent de sagesse, simple ou impactée.' },
        { step: '04', title: 'Récupération', desc: 'Instructions post-opératoires détaillées et suivi téléphonique.' },
      ],
      faq: [
        { q: 'Est-ce douloureux?', a: "Non — l'anesthésie locale élimine la douleur pendant la procédure. Un léger inconfort peut survenir les jours suivants, contrôlé par analgésiques." },
        { q: 'Combien de temps dure la procédure?', a: 'Entre 30 et 60 minutes selon la complexité.' },
        { q: 'Dois-je retirer les 4 en même temps?', a: 'Pas nécessairement. Le Dr Chaussé évalue chaque cas et recommande le plan le plus adapté.' },
        { q: 'Quel est le temps de récupération?', a: 'En général 2 à 4 jours. La plupart des patients reprennent leurs activités rapidement.' },
      ],
      videoId: null,
      videoTitle: null,
    },
    parodontie: {
      slug: 'parodontie',
      title: 'Service de Parodontie',
      metaTitle: 'Parodontie Montréal | Dr Serge Chaussé — Traitement des gencives',
      metaDescription: "Curetage parodontal, chirurgie et greffe gingivale à Montréal. Dr Serge Chaussé, expert en santé des gencives depuis 40 ans.",
      hero: {
        tagline: 'Santé des gencives, santé pour la vie',
        title: 'Service de Parodontie',
        subtitle: "La parodontie traite les maladies des gencives et des structures qui soutiennent vos dents. Un traitement efficace est essentiel à votre santé bucco-dentaire à long terme.",
      },
      intro: "La maladie parodontale est l'une des causes principales de perte de dents chez l'adulte. Le Dr Chaussé offre une gamme complète de traitements parodontaux pour stopper la progression de la maladie et restaurer la santé de vos gencives.",
      benefits: [
        { icon: '🔬', title: 'Curetage parodontal', desc: 'Nettoyage en profondeur sous les gencives pour éliminer la plaque et le tartre.' },
        { icon: '⚕️', title: 'Chirurgie parodontale', desc: 'Intervention chirurgicale pour traiter les cas avancés.' },
        { icon: '🌱', title: 'Greffe gingivale', desc: 'Restauration des gencives récédées pour protéger les racines exposées.' },
        { icon: '📅', title: 'Maintenance parodontale', desc: 'Suivi régulier pour maintenir la santé des gencives à long terme.' },
      ],
      process: [
        { step: '01', title: 'Examen parodontal', desc: 'Mesure des poches parodontales et évaluation complète de la santé des gencives.' },
        { step: '02', title: 'Détartrage et surfaçage', desc: 'Nettoyage en profondeur sous les gencives pour éliminer les dépôts bactériens.' },
        { step: '03', title: 'Traitement chirurgical', desc: 'Si nécessaire, chirurgie ou greffe pour restaurer les tissus parodontaux.' },
        { step: '04', title: 'Maintenance', desc: 'Visites de contrôle régulières pour maintenir les résultats obtenus.' },
      ],
      faq: [
        { q: 'Qu\'est-ce que la maladie parodontale?', a: "C'est une infection des tissus qui soutiennent les dents. Non traitée, elle peut mener à la perte des dents." },
        { q: 'Quels sont les signes d\'alerte?', a: 'Gencives qui saignent, rouges ou gonflées, mauvaise haleine persistante, dents qui bougent.' },
        { q: 'Le traitement est-il douloureux?', a: "Le curetage se fait sous anesthésie locale. L'inconfort post-traitement est minimal." },
        { q: 'Peut-on prévenir la maladie parodontale?', a: 'Oui — hygiène rigoureuse, visites régulières et détartrage professionnel sont les meilleures préventions.' },
      ],
      videoId: null,
      videoTitle: null,
    },
    chirurgie: {
      slug: 'chirurgie-osseuse',
      title: 'Chirurgie osseuse & Greffe',
      metaTitle: 'Greffe osseuse dentaire Montréal | Dr Serge Chaussé',
      metaDescription: "Greffe osseuse et chirurgie osseuse à Montréal. Régénération osseuse avant implants. Dr Chaussé, chirurgien-dentiste expert depuis 40 ans.",
      hero: {
        tagline: 'La fondation de votre sourire',
        title: 'Chirurgie osseuse & Greffe',
        subtitle: "Quand l'os manque, nous le reconstruisons. Les techniques de greffe osseuse modernes permettent à presque tous les patients d'être candidats aux implants.",
      },
      intro: "La greffe osseuse dentaire est une procédure qui vise à régénérer ou augmenter le volume osseux de la mâchoire avant la pose d'implants. Le Dr Chaussé maîtrise l'ensemble des techniques de régénération osseuse guidée (ROG), de sinus lift et de greffes autogènes.",
      benefits: [
        { icon: '🏗️', title: 'Reconstruction complète', desc: 'Même les cas de résorption avancée peuvent être traités.' },
        { icon: '🧬', title: 'Matériaux biocompatibles', desc: 'Greffes autogènes, allogreffes ou substituts synthétiques selon votre cas.' },
        { icon: '🎯', title: 'Précision chirurgicale', desc: "40 ans d'expérience en chirurgie orale avancée." },
        { icon: '✅', title: 'Préparation aux implants', desc: "Crée les conditions idéales pour une ostéointégration optimale." },
      ],
      process: [
        { step: '01', title: 'Évaluation radiologique', desc: 'Scanner 3D pour mesurer précisément le volume osseux disponible.' },
        { step: '02', title: 'Plan de traitement', desc: 'Choix du type de greffe et planification de la chirurgie.' },
        { step: '03', title: 'Chirurgie de greffe', desc: 'Pose du matériau de greffe et membrane de protection sous anesthésie locale.' },
        { step: '04', title: "Guérison et pose d'implants", desc: '4 à 9 mois de cicatrisation avant la pose des implants.' },
      ],
      faq: [
        { q: "D'où vient l'os pour la greffe?", a: "Selon le cas : os autogène (votre propre os), allogreffe (banque d'os), xénogreffe (origine bovine) ou substitut synthétique. Le Dr Chaussé recommande la meilleure option pour votre situation." },
        { q: 'Est-ce douloureux?', a: "La chirurgie se fait sous anesthésie locale. Des douleurs légères sont normales les premiers jours, bien contrôlées par des analgésiques." },
        { q: 'Combien de temps avant les implants?', a: "De 4 à 9 mois selon le type de greffe et votre capacité de régénération osseuse." },
        { q: 'Quel est le taux de succès?', a: "Les greffes osseuses modernes ont un taux de succès supérieur à 90% lorsqu'elles sont réalisées par un chirurgien expérimenté." },
      ],
      videoId: 'yzym5yC81RU',
      videoTitle: 'Chirurgie osseuse expliquée par Dr Chaussé',
    },
    atm: {
      slug: 'douleur-atm-botox',
      title: 'Douleur ATM & Botox thérapeutique',
      metaTitle: 'Traitement douleur ATM Montréal | Botox dentaire | Dr Chaussé',
      metaDescription: "Traitement des douleurs de l'articulation temporo-mandibulaire (ATM) et botox thérapeutique à Montréal. Soulagement rapide et durable.",
      hero: {
        tagline: 'Fin aux douleurs de mâchoire',
        title: 'Douleur ATM & Botox thérapeutique',
        subtitle: "Les douleurs de mâchoire, claquements et maux de tête liés à l'ATM peuvent être traités efficacement. Le botox thérapeutique offre un soulagement rapide et durable.",
      },
      intro: "L'articulation temporo-mandibulaire (ATM) est l'une des articulations les plus complexes du corps. Quand elle dysfonctionne, elle peut causer des douleurs faciales, des maux de tête, des claquements et des difficultés à ouvrir la bouche. Le Dr Chaussé propose des traitements innovants incluant le botox thérapeutique.",
      benefits: [
        { icon: '😌', title: 'Soulagement rapide', desc: 'Le botox agit en 3-7 jours pour relâcher les muscles hypertoniques.' },
        { icon: '🎯', title: 'Traitement ciblé', desc: 'Injections précises dans les muscles masséters et temporaux.' },
        { icon: '⏰', title: 'Durée 4-6 mois', desc: 'Un traitement dure de 4 à 6 mois, renouvelable selon les besoins.' },
        { icon: '💊', title: 'Alternative aux médicaments', desc: "Réduisez ou éliminez le besoin d'analgésiques au quotidien." },
      ],
      process: [
        { step: '01', title: 'Évaluation ATM', desc: "Examen clinique complet, analyse de l'occlusion et des habitudes parafonctionnelles." },
        { step: '02', title: 'Diagnostic', desc: 'Identification précise de la source des douleurs (musculaire, articulaire, mixte).' },
        { step: '03', title: 'Plan de traitement', desc: 'Combinaison possible : gouttière occlusale + botox + physiothérapie.' },
        { step: '04', title: 'Injections Botox', desc: "Séance d'injections rapide (15-20 min) directement en cabinet." },
      ],
      faq: [
        { q: "Comment savoir si j'ai un problème d'ATM?", a: "Symptômes typiques : claquements à l'ouverture/fermeture, douleurs musculaires faciales, maux de tête matinaux, grincement de dents (bruxisme), difficulté à ouvrir grand la bouche." },
        { q: 'Le botox est-il sécuritaire?', a: "Oui, le botox thérapeutique est utilisé en dentisterie depuis plus de 20 ans. Les doses utilisées pour l'ATM sont faibles et bien tolérées." },
        { q: "Combien d'unités de botox sont nécessaires?", a: 'Généralement entre 40 et 60 unités par côté pour les masséters, selon leur taille et la sévérité du bruxisme.' },
        { q: 'Est-ce remboursé par les assurances?', a: 'Certains régimes couvrent le botox thérapeutique pour les indications médicales. Nous pouvons vous aider à préparer la documentation.' },
      ],
      videoId: 'k649xMCcHLo',
      videoTitle: 'Dr Chaussé explique le traitement ATM',
    },
    orthodontie: {
      slug: 'orthodontie-invisalign',
      title: 'Orthodontie & Invisalign',
      metaTitle: 'Invisalign Montréal | Orthodontie adulte | Dr Serge Chaussé',
      metaDescription: 'Orthodontie et aligneurs transparents Invisalign à Montréal. Corrigez votre sourire discrètement. Dr Chaussé, dentiste spécialisé depuis 40 ans.',
      hero: {
        tagline: 'Le sourire aligné sans compromis',
        title: 'Orthodontie & Invisalign',
        subtitle: "Corrigez l'alignement de vos dents discrètement avec les aligneurs transparents. Une alternative moderne et confortable aux broches traditionnelles.",
      },
      intro: "L'orthodontie moderne a été révolutionnée par les aligneurs transparents. Invisalign et les systèmes similaires permettent de corriger la majorité des malpositions dentaires avec des gouttières transparentes, amovibles et presque invisibles. Le Dr Chaussé évalue chaque cas pour recommander la meilleure approche.",
      benefits: [
        { icon: '👻', title: 'Presque invisible', desc: 'Les aligneurs transparents sont quasi-indétectables au quotidien.' },
        { icon: '🍎', title: 'Amovibles', desc: 'Retirez les aligneurs pour manger, boire et vous brosser les dents.' },
        { icon: '😊', title: 'Confortables', desc: "Pas de bagues, de fils ou d'ajustements douloureux chaque mois." },
        { icon: '📱', title: 'Technologie 3D', desc: 'Visualisez le résultat final avant même de commencer le traitement.' },
      ],
      process: [
        { step: '01', title: 'Consultation et scan', desc: 'Scan numérique 3D de vos dents. Aucune empreinte traditionnelle désagréable.' },
        { step: '02', title: 'Simulation du résultat', desc: 'Visualisation 3D de la progression et du résultat final attendu.' },
        { step: '03', title: 'Fabrication des aligneurs', desc: 'Série d\'aligneurs sur mesure fabriqués en laboratoire spécialisé.' },
        { step: '04', title: 'Suivi et résultat', desc: 'Visites de contrôle aux 6-8 semaines. Résultat en 6 à 18 mois selon la complexité.' },
      ],
      faq: [
        { q: 'Suis-je candidat à Invisalign?', a: "La majorité des adultes et adolescents peuvent être traités avec Invisalign. Les cas très complexes peuvent nécessiter des broches traditionnelles. Une évaluation gratuite permet de le déterminer." },
        { q: 'Combien d\'heures par jour faut-il porter les aligneurs?', a: '20 à 22 heures par jour. Vous les retirez uniquement pour manger et vous brosser les dents.' },
        { q: 'Est-ce douloureux?', a: "Une légère pression est normale les premiers jours de chaque nouvel aligneur. Rien de comparable aux ajustements de broches traditionnelles." },
        { q: "Quel est le prix d'Invisalign?", a: "Le coût varie de 3 500$ à 8 000$ selon la complexité. Des plans de financement sont disponibles. Certaines assurances couvrent une partie du traitement." },
      ],
      videoId: 'yzym5yC81RU',
      videoTitle: 'Orthodontie et Invisalign avec Dr Chaussé',
    },
    botoxEsthetique: {
      slug: 'botox-esthetique',
      title: 'Botox esthétique',
      metaTitle: 'Botox esthétique Montréal | Rides | Dr Serge Chaussé Dentiste',
      metaDescription: 'Botox esthétique et rides à Montréal par Dr Serge Chaussé. Expert en injections faciales, résultats naturels. Consultation en cabinet dentaire.',
      hero: {
        tagline: 'Beauté naturelle et harmonieuse',
        title: 'Botox esthétique',
        subtitle: "Le dentiste est l'expert de l'anatomie faciale. Des injections de botox esthétique précises pour un résultat naturel qui sublime votre sourire.",
      },
      intro: "Le dentiste est l'un des professionnels les mieux qualifiés pour administrer le botox esthétique. Sa connaissance approfondie de l'anatomie faciale, des muscles, des nerfs et des vaisseaux de la région oro-faciale garantit des injections précises et sécuritaires.",
      benefits: [
        { icon: '✨', title: 'Expertise anatomique', desc: "Personne ne connaît mieux l'anatomie de votre visage qu'un dentiste." },
        { icon: '🎨', title: 'Résultat naturel', desc: 'Approche conservatrice pour préserver votre expression naturelle.' },
        { icon: '⚡', title: 'Séance rapide', desc: 'Traitement de 20-30 minutes en cabinet, aucune récupération nécessaire.' },
        { icon: '🌟', title: 'Complément du sourire', desc: 'Harmonisez votre sourire avec le reste de votre visage.' },
      ],
      process: [
        { step: '01', title: 'Consultation esthétique', desc: 'Analyse du visage, identification des zones à traiter, discussion des attentes.' },
        { step: '02', title: 'Plan de traitement', desc: 'Dosage personnalisé pour un résultat naturel et harmonieux.' },
        { step: '03', title: 'Injections', desc: 'Séance rapide de 20-30 minutes avec micro-aiguilles ultra-fines.' },
        { step: '04', title: 'Suivi', desc: 'Réévaluation à 2 semaines pour ajustements si nécessaire.' },
      ],
      faq: [
        { q: 'Pourquoi choisir un dentiste pour le botox?', a: "Les dentistes ont des milliers d'heures de pratique en anatomie faciale, en anesthésie et en injections de précision. Ils sont parmi les mieux formés pour ce type de procédure." },
        { q: 'Quelles zones peuvent être traitées?', a: "Rides du front, rides du lion (entre les sourcils), pattes d'oie, sourcils tombants, rides du cou, sourire gingival." },
        { q: 'Combien de temps durent les résultats?', a: 'Généralement 3 à 4 mois pour un premier traitement, puis 4 à 6 mois avec des traitements réguliers.' },
        { q: "Y a-t-il des effets secondaires?", a: "Légères rougeurs ou ecchymoses possibles au site d'injection, disparaissant en 24-48h. Les effets secondaires sérieux sont extrêmement rares avec un praticien qualifié." },
      ],
      videoId: 'k649xMCcHLo',
      videoTitle: 'Botox esthétique par Dr Chaussé',
    },
    rehabilitation: {
      slug: 'rehabilitation-complete',
      title: 'Réhabilitation complète',
      metaTitle: 'Réhabilitation dentaire complète Montréal | Dr Serge Chaussé',
      metaDescription: 'Réhabilitation dentaire complète sur implants et dents naturelles à Montréal. Transformation complète du sourire par Dr Chaussé, expert depuis 40 ans.',
      hero: {
        tagline: 'La transformation totale',
        title: 'Réhabilitation complète',
        subtitle: "Quand plusieurs dents sont compromises, une réhabilitation complète permet de reconstruire un sourire fonctionnel et esthétique en coordonnant tous les traitements nécessaires.",
      },
      intro: "La réhabilitation dentaire complète est l'approche globale qui combine plusieurs disciplines dentaires pour restaurer la fonction, l'esthétique et la santé de toute la bouche. Que ce soit sur implants, sur dents naturelles ou une combinaison des deux, le Dr Chaussé conçoit des plans de traitement sur mesure.",
      benefits: [
        { icon: '🏆', title: 'Approche globale', desc: 'Traitement coordonné de toutes les problématiques en un seul plan.' },
        { icon: '🎯', title: 'Sur mesure', desc: 'Chaque réhabilitation est unique, adaptée à votre anatomie et vos objectifs.' },
        { icon: '⚖️', title: 'Équilibre occlusal', desc: "Restauration d'une occlusion parfaite pour prévenir les récidives." },
        { icon: '😍', title: 'Transformation esthétique', desc: 'Un nouveau sourire qui reflète qui vous êtes vraiment.' },
      ],
      process: [
        { step: '01', title: 'Bilan complet', desc: "Radiographies, photos, modèles d'étude, analyse de l'occlusion." },
        { step: '02', title: 'Planification virtuelle', desc: 'Wax-up diagnostique ou simulation numérique du résultat final.' },
        { step: '03', title: 'Phase préparatoire', desc: 'Traitement des problèmes parodontaux, extractions, greffes si nécessaire.' },
        { step: '04', title: 'Restaurations', desc: 'Pose des implants, couronnes, facettes selon le plan établi.' },
      ],
      faq: [
        { q: 'Combien de temps dure une réhabilitation complète?', a: "De 6 mois à 2 ans selon la complexité. Les cas impliquant des implants et des greffes osseuses nécessitent plus de temps." },
        { q: 'Puis-je avoir des dents temporaires pendant le traitement?', a: "Absolument. Des prothèses provisoires esthétiques sont prévues pour que vous n'ayez jamais à vous priver de sourire pendant le traitement." },
        { q: 'Comment se fait la planification?', a: "Grâce aux technologies numériques modernes (scan 3D, logiciels de planification), vous pouvez visualiser le résultat final avant même de commencer." },
        { q: 'Quels types de restaurations sont utilisées?', a: "Couronnes en zircone, facettes en céramique, bridges sur implants ou naturels, selon les besoins de chaque dent ou zone." },
      ],
      videoId: 'D4OhKuY25do',
      videoTitle: 'Réhabilitation complète par Dr Chaussé',
    },
  },
  en: {
    implants: {
      slug: 'dental-implants',
      title: 'Dental Implants',
      metaTitle: 'Dental Implants Montreal | Dr Serge Chaussé',
      metaDescription: 'Expert dental implants in Montreal. 40 years of experience. Dr Serge Chaussé offers permanent solutions for missing teeth. Free consultation.',
      hero: {
        tagline: 'The permanent solution',
        title: 'Dental Implants',
        subtitle: 'Restore your natural smile and full chewing function with titanium dental implants placed by an expert with 40 years of experience.',
      },
      intro: "Dental implants are today's most advanced solution for replacing one or more missing teeth. Unlike removable dentures or bridges, implants integrate directly into the jawbone, offering stability and appearance identical to a natural tooth.",
      benefits: [
        { icon: '🦷', title: 'Permanent result', desc: 'A well-placed implant lasts a lifetime with minimal maintenance.' },
        { icon: '💪', title: 'Maximum strength', desc: 'Eat, talk and smile without restriction or discomfort.' },
        { icon: '🎨', title: 'Natural aesthetics', desc: 'The crown is custom-made to blend in perfectly.' },
        { icon: '🦴', title: 'Bone preservation', desc: 'The implant stimulates bone and prevents resorption.' },
      ],
      process: [
        { step: '01', title: 'Consultation and exam', desc: '3D X-rays, health assessment, personalized treatment plan.' },
        { step: '02', title: 'Implant placement', desc: 'Surgical insertion of the titanium screw under local anesthesia.' },
        { step: '03', title: 'Osseointegration', desc: '3 to 6 month healing period where bone fuses with the implant.' },
        { step: '04', title: 'Final crown', desc: 'Custom crown placement. Natural and lasting final result.' },
      ],
      faq: [
        { q: 'Is it painful?', a: 'The procedure is done under local anesthesia. Most patients compare the experience to a tooth extraction. Pain relievers are sufficient after the procedure.' },
        { q: 'How long does an implant last?', a: 'A well-integrated implant can last a lifetime. Long-term studies show success rates above 95% after 20 years.' },
        { q: 'Am I a good candidate?', a: 'Most healthy adults are eligible. A bone examination and health assessment will confirm your candidacy.' },
        { q: 'What is the cost?', a: 'Cost varies depending on the number of implants and preparatory treatments. A consultation will establish a precise quote. Some insurance plans cover part of the cost.' },
      ],
      videoId: 'k649xMCcHLo',
      videoTitle: 'Dr Chaussé explains dental implants',
    },
  },
};

export const servicesList = {
  fr: [
    { slug: 'implants-dentaires', title: 'Implants dentaires', icon: '🦷', color: '#287b55' },
    { slug: 'all-on-4', title: 'All-on-4', icon: '⚡', color: '#1a4131' },
    { slug: 'chirurgie-dents-de-sagesse', title: 'Chirurgie des dents de sagesse', icon: '🦷', color: '#226346' },
    { slug: 'parodontie', title: 'Service de Parodontie', icon: '🫦', color: '#287b55' },
    { slug: 'chirurgie-osseuse', title: 'Chirurgie osseuse & Greffe', icon: '🦴', color: '#1a4131' },
    { slug: 'douleur-atm-botox', title: 'Douleur ATM & Botox thérapeutique', icon: '😌', color: '#226346' },
    { slug: 'orthodontie-invisalign', title: 'Orthodontie & Invisalign', icon: '😊', color: '#287b55' },
    { slug: 'botox-esthetique', title: 'Botox esthétique', icon: '✨', color: '#1a4131' },
    { slug: 'rehabilitation-complete', title: 'Réhabilitation complète', icon: '🏆', color: '#226346' },
  ],
  en: [
    { slug: 'dental-implants', title: 'Dental Implants', icon: '🦷', color: '#287b55' },
  ],
};
